apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-nginx-deployment-co
  namespace: dev
  labels:
    app: nginx
    project: dev
    tag: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-nginx1-deployment-co
  namespace: dev
  labels:
    app: nginx1
    project: dev
    tag: common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
