apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: create-deployment-delete
  namespace: ccb
spec:
  schedule: "00 02 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ccb
          containers:
          - name: hello
            image: nightfury1204/alpine-curl
            imagePullPolicy: IfNotPresent
            command: [ 'sh', '-c' ,'curl  --insecure -X DELETE -H "Content-Type: application/json"  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"  "https://kubernetes.default.svc.cluster.local/apis/apps/v1/namespaces/ccb/deployments?pretty=true&fieldSelector=metadata.name%3Ddeployment-created"']
          restartPolicy: OnFailure
